# Generated by Django 4.0.2 on 2022-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='photo',
            field=models.ImageField(default='user.png', upload_to='professorPhoto'),
        ),
    ]
