# Generated by Django 4.0.2 on 2022-02-21 12:53

from django.db import migrations, models
import news.utlis


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ImageField(default=1, upload_to=news.utlis.cover_directory_path),
            preserve_default=False,
        ),
    ]
