# Generated by Django 4.0.2 on 2022-02-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ad',
            field=models.BooleanField(default=False),
        ),
    ]
